### ISSUE TITLE
Make the oracle work on polygon network (or other network)

### ISSUE THREAD

**Issue by foufrix** [humanprotocol/fortune#15]
I deployed the Factory Escrow contract here: https://mumbai.polygonscan.com/address/0x2dd72db2bBA65cE663e476bA8b84A1aAF802A8e3
And I deployed it to work with USDC (for easy testing): https://mumbai.polygonscan.com/address/0xe11a86849d99f524cac3e7a0ec1241828e332c62

In `constants.js` I changed the value to make it work : 
```javascript
export const HMT_ADDRESS = "0xe11A86849d99F524cAC3E7A0Ec1241828e332C62";
export const ESCROW_FACTORY_ADDRESS = "0x2dd72db2bBA65cE663e476bA8b84A1aAF802A8e3";
```

I started the fortune exchange and launcher docker image locally. Creation of Escrow worked ok. Funding the Escrow (with USDC) and providing manifest.json worked ok.

<img width="1225" alt="image" src="https://user-images.githubusercontent.com/16646581/163677926-3a52c255-b6b5-4277-8f3e-ff97103bc34e.png">

Here is the manifest I provide : 
```json
{
"job_title": "Requesting fortunes from the fortunes teller",
"job_type": "fortune",
"fortunes_requested": 2,
"recording_oracle_address": "0x61F9F0B31eacB420553da8BCC59DC617279731Ac",
"reputation_oracle_address": "0xD979105297fB0eee83F7433fC09279cb5B94fFC6",
"echange_oracle_address": "0x6b7E3C31F34cF38d1DFC1D9A8A59482028395809",
"recording_oracle_url": "http://ec2-3-15-230-238.us-east-2.compute.amazonaws.com:3005/job/results",
"reputation_oracle_url": "http://ec2-3-15-230-238.us-east-2.compute.amazonaws.com:3006/job/results",
"exchange_oracle_url": "http://ec2-3-15-230-238.us-east-2.compute.amazonaws.com:3001/"
}
```

I get the exchange URL, I can go to it, but when I want to send the fortune message from Agent 2 and 3 accounts, I get this error :
![image](https://user-images.githubusercontent.com/16646581/163677602-1d937bda-81df-424b-8caa-750aba71e93d.png)

From my understanding, the oracles are running on this RPC http://ec2-3-15-230-238.us-east-2.compute.amazonaws.com:8545/  hosted on Amazon AWS. 

Can the polygon Escrow contract created on Polygon Mumbai interact with the oracles hosted on AWS? If yes, what do I need to change? 

Because on the AWS chain, the fortune app works ok.

**Comment by kaseLunt** [comment]
Having the same issue on Moonbeam

**Comment by posix4e** [comment]
@kaseLunt @foufrix Do you see anything in the logs on the oracles?

**Comment by vkomodey** [comment]
Hey guys! Fortune is not multichain right now and can be configured via environment variables(backends). There are 2 ways of doing this:

1. You deploy fortune to some free hosting(like heroku) for a particular blockchain(Moonbeam for example)
2. Or we will add the multichain support and deploy it to some test network
3. After proper contracts testing we will deploy fortune to the existing setup with some testnet

Personally I don't think that we need a multichain right now. New chain = new instance is the best way right now

**Comment by posix4e** [comment]
1) Agreed, no reason to change the source.
2) It would be good to see a video and for you to share the environment variables. You can do this by forking the repo, and we will add a link in documentation to your fork
3) Vlad provides a good example of using a free services like heroku. This will make the environment variables more clear

**Comment by foufrix** [comment]
It's a bit complicated to deploy on heroku because they allow only one port, so it's always a different link and instance need to be deployed one by one, I'm not even sure it would work as reputation and recording oracles would not be on the same instance.

Anyway by running everything locally and changing `constants.js` to use contract on Polygon Mumbai and USDC for the moment, I manage to :
1. launch app and create escrow interacting with contract on Mumbai
2. Fund contract with USDC and provide manifest.json using only localhost
3. Launching the exchange, trying to send Fortune Message over Polygon Mumbai, I get the same error as what I had when interacting with the AWS instance :
![image](https://user-images.githubusercontent.com/16646581/164431791-bdd4fc5a-ed2e-4fcd-9167-32fa22ab939a.png)
But this time I have the backend logs : 
![image](https://user-images.githubusercontent.com/16646581/164431899-084e950f-bbdb-4536-98b1-7616ff3f16e2.png)

After some search on this error, it can be cause by a wrong ABI. 

I launched the exchange without docker to debug, and I see that there is an error when setting up the main escrow here : 
```javascript
  const setMainEscrow = async (address) => {
    setEscrow(address);
    console.log("address: ", address);
    const Escrow = new web3.eth.Contract(EscrowABI, address);
    console.log("1");
    const escrowSt = await Escrow.methods.status().call();
    console.log("2");
    setEscrowStatus(statusesMap[escrowSt]);

    const balance = await Escrow.methods.getBalance().call();
    setBalance(web3.utils.fromWei(balance, "ether"));
    console.log("3");

    const manifestUrl = await Escrow.methods.manifestUrl().call();
    if (manifestUrl) {
      const manifestContent = (await axios.get(manifestUrl)).data;

      setRecordingOracleUrl(manifestContent.recording_oracle_url);
    }
  };
```

And the logs on the frontend :
![image](https://user-images.githubusercontent.com/16646581/164440432-40094fc7-90b3-44fc-b514-96571475396d.png)

We see that the function crash directly at `Escrow.methods.status().call()` 
DO you have any idea what need to be changed in `/contracts/EscrowAbi.json` to work with Polygon contract ?

**Comment by vkomodey** [comment]
Hey @foufrix . Let's replace the Escrow ABI with this implementation - https://github.com/humanprotocol/hmt-escrow/pull/295/files

It supports the standard ERC20 interface without bulk* methods

**Comment by foufrix** [comment]
Hi, @vkomodey thanks for the help,

I deployed the contract of your branch polygon-escrow-bulk here: https://mumbai.polygonscan.com/address/0x5D65C42cF4a140863744889BAd07f246C0211754

I tried again, creating an Escrow and redoing everything, I still got the same error on the call of the oracle :
Front
![image](https://user-images.githubusercontent.com/16646581/164458685-71731b0e-74e2-4c9b-a3f4-89fd413743bc.png)

Back 
<img width="1250" alt="image" src="https://user-images.githubusercontent.com/16646581/164458736-5d569981-414d-43fe-bebc-444742f5ce04.png">

Is it my guess there may be a mismatch of networks?

Because the `from : 0x61f9f0b31eacb420553da8bcc59dc617279731ac` it's the oracle on local ganache and `to : 0x4f7106aac91ca6d1e6fef1d6f114baeb7643cdf8` is the Escrow created on [Polygon Mumbai](https://mumbai.polygonscan.com/address/0x4f7106aac91ca6d1e6fef1d6f114baeb7643cdf8)

Can a local call from the oracle on ganache to the polygon network work? And maybe the code of the oracle is trying to reach the contract 0x4f7106aac91ca6d1e6fef1d6f114baeb7643cdf8 on ganache instead on polygon

**Comment by vkomodey** [comment]
> Because the from : 0x61f9f0b31eacb420553da8bcc59dc617279731ac it's the oracle on local ganache and to : 0x4f7106aac91ca6d1e6fef1d6f114baeb7643cdf8 is the Escrow created on [Polygon Mumbai](https://mumbai.polygonscan.com/address/0x4f7106aac91ca6d1e6fef1d6f114baeb7643cdf8)

Are you trying this on the deployed playground? I mean, we definitely can't use current oracles deployed in the ganache setup

>Can a local call from the oracle on ganache to the polygon network work?
Definitely not. Let me check this tomorrow

**Comment by foufrix** [comment]
>Are you trying this on the deployed playground? I mean, we definitely can't use current oracles deployed in the ganache setup

It's not on the AWS deployed ganache, but on a local ganache instance on my computer

I thought we could, I asked on the discord about that and it did not seem to be an issue.
So I need to deploy oracle as well on the polygon Mumbai network?

**Comment by vkomodey** [comment]
So I need to deploy oracle as well on the polygon Mumbai network?

Oracle is not a contract. It's EOA. You don't have to deploy anything here
