### ISSUE TITLE
Fortune app not working locally

### ISSUE THREAD

**Issue by foufrix** [humanprotocol/fortune#17]
Step : 
1. clone repo
2. docker-compose up
3. Check that all docker instance are running
![image](https://user-images.githubusercontent.com/16646581/164483292-c3d78ab4-5dd5-4fdc-bce3-96d23e6fd749.png)
4. Deploy contract on the chain (cd contracts && truffle migrate development)
5. Connect to network with metamask (http://localhost:8547 and id 1337)
6. Import HMT token (0x444c45937D2202118a0FF9c48d491cef527b59dF)
7. Go to launcher on localhost 3000 
8. Create Escrow with first account (28e516f1e2f99e96a48a23cea1f94ee5f073403a1c68e818263f0eb898f1c8e5)
9. Fund Escrow with HMT
10. Add manifest.json : 
```json
{
"job_title": "Requesting fortunes from the fortunes teller",
"job_type": "fortune",
"fortunes_requested": 2,
"recording_oracle_address": "0x61F9F0B31eacB420553da8BCC59DC617279731Ac",
"reputation_oracle_address": "0xD979105297fB0eee83F7433fC09279cb5B94fFC6",
"echange_oracle_address": "0x6b7E3C31F34cF38d1DFC1D9A8A59482028395809",
"recording_oracle_url": "http://localhost:3005/job/results",
"reputation_oracle_url": "http://localhost:3006/job/results",
"exchange_oracle_url": "http://localhost:3001/"
}
```
11. Go to localhost:9001, log with dev and devdevdev, create a bucket job-results (does not exist when first deploy)
12. Go to exchange, send first message with account 2 (9e531b326f8c09437ab2af7a768e5e25422b43075169714f1790b6b036f73b00)
13. Send 2nd message with account 3 (9da0d3721774843193737244a0f3355191f66ff7321e83eae83f7f746eb34350)

Get an error :
From exchange
![image](https://user-images.githubusercontent.com/16646581/164484623-ac3e6da8-5a6a-4036-941f-fc13a44d6ec5.png)

From Backend
![image](https://user-images.githubusercontent.com/16646581/164484681-34298456-a27a-4de3-8697-065afb186f0e.png)

**Comment by vkomodey** [comment]
Hey, @foufrix . Thanks for the issue! Yes, the problem is in the incorrect address of the reputation oracle in the manifest.json. I've updated docker-compose setup as well as manifest in the PR #19

**Comment by foufrix** [comment]
Hi @vkomodey just to be sure, I don't see any modification of `manifest.json` nor `docker-compose.yml` in #19 it's normal?
I've tried to make it run, on a new ganache setup : 
1. Pulling the change
2. Remove previous docker instance, Building new code with docker
3. Deploying contract
<img width="701" alt="image" src="https://user-images.githubusercontent.com/16646581/165058561-ae61ec9f-0f69-49e1-80e1-a1fcd637593f.png">
4. Check that it's same that what's in `constants.js` OK
5. Launching launcher, create escrow => transaction failed
<img width="1199" alt="image" src="https://user-images.githubusercontent.com/16646581/165058516-42e21bb1-7533-4758-b8bd-16bfe8b21778.png">

Am I doing something wrong? Does it work on your side? This was working prior to #19

**Comment by vkomodey** [comment]
Manifest changed [here](https://github.com/humanprotocol/fortune/pull/19/files#diff-ffa5b716b5a57837f7929dfcca4b4dfdeb97210a7fd5a12d2f1978846d6f1743R9)

Please check your manifest has same URLs to oracles as in the code right now(especially the reputation oracle)

Steps are right. You should pull fresh master and do a re-run of the whole docker-compose setup

**Comment by foufrix** [comment]
Yes effectively for the manifest I'm blind sorry about that. Saw that this refers to docker-compose config.

Solved the error I've pinged about by resetting metamask transaction (error in Tx)

But I'm still having the issue on the call of the Agent 3 when putting the 2nd message on the Escrow :
1. Setup escrow with escrow address, filling it with HMT and providing manifest.json
```json
{
  "job_title": "Requesting fortunes from the fortunes teller",
  "job_type": "fortune",
  "fortunes_requested": 2,
  "recording_oracle_address": "0x61F9F0B31eacB420553da8BCC59DC617279731Ac",
  "reputation_oracle_address": "0xD979105297fB0eee83F7433fC09279cb5B94fFC6",
  "echange_oracle_address": "0x6b7E3C31F34cF38d1DFC1D9A8A59482028395809",
  "recording_oracle_url": "http://localhost:3005/job/results",
  "reputation_oracle_url": "http://reputation-oracle:3006/job/results",
  "exchange_oracle_url": "http://localhost:3001"
}
```
2. Using the address of agent 2 to send a message => OK
3. Using the address of agent 3 to send a message => KO

Still the same issue as before : 
<img width="751" alt="image" src="https://user-images.githubusercontent.com/16646581/165125478-5f3d2fa3-e539-471b-af9c-36dc018e436e.png">

And here is the log from the docker image of reputation oracle, I've added a log of the `reputationOracleUrl` to be sure that we have the good one : 
```logs
Recording Oracle server listening port 3005

Doing bulk payouts

reputationOracleUrl:  http://reputation-oracle:3005/job/results

Error

Error: connect ECONNREFUSED 172.28.0.3:3005

    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1161:16) {

  errno: -111,

  code: 'ECONNREFUSED',

  syscall: 'connect',

  address: '172.28.0.3',

  port: 3005,

  config: {

    transitional: {

      silentJSONParsing: true,

      forcedJSONParsing: true,

      clarifyTimeoutError: false

    },

    adapter: [Function: httpAdapter],

    transformRequest: [ [Function: transformRequest] ],

    transformResponse: [ [Function: transformResponse] ],

    timeout: 0,

    xsrfCookieName: 'XSRF-TOKEN',

    xsrfHeaderName: 'X-XSRF-TOKEN',

    maxContentLength: -1,

    maxBodyLength: -1,

    validateStatus: [Function: validateStatus],

    headers: {

      Accept: 'application/json, text/plain, */*',

      'Content-Type': 'application/json',

      'User-Agent': 'axios/0.25.0',

      'Content-Length': 227

    },

    method: 'post',

    url: 'http://reputation-oracle:3005/job/results',

    data: '{"escrowAddress":"0xE382BaD171463297C92D5192b7cD24A5F213Ee28","fortunes":[{"worker":"0xB113043105b06e98776A74b796Eb40e451C717B9","fortune":"Agent 2"},{"worker":"0x92a2eEF7Ff696BCef98957a0189872680600a959","fortune":"Agent 3"}]}'

  },

  request: <ref *1> Writable {

    _writableState: WritableState {

      objectMode: false,

      highWaterMark: 16384,

      finalCalled: false,

      needDrain: false,

      ending: false,

      ended: false,

      finished: false,

      destroyed: false,

      decodeStrings: true,

      defaultEncoding: 'utf8',

      length: 0,

      writing: false,

      corked: 0,

      sync: true,

      bufferProcessing: false,

      onwrite: [Function: bound onwrite],

      writecb: null,

      writelen: 0,

      afterWriteTickInfo: null,

      buffered: [],

      bufferedIndex: 0,

      allBuffers: true,

      allNoop: true,

      pendingcb: 0,

      constructed: true,

      prefinished: false,

      errorEmitted: false,

      emitClose: true,

      autoDestroy: true,

      errored: null,

      closed: false,

      closeEmitted: false,

      [Symbol(kOnFinished)]: []

    },

    _events: [Object: null prototype] {

      response: [Function: handleResponse],

      error: [Function: handleRequestError],

      socket: [Function: handleRequestSocket]

    },

    _eventsCount: 3,

    _maxListeners: undefined,

    _options: {

      maxRedirects: 21,

      maxBodyLength: 10485760,

      protocol: 'http:',

      path: '/job/results',

      method: 'POST',

      headers: [Object],

      agent: undefined,

      agents: [Object],

      auth: undefined,

      hostname: 'reputation-oracle',

      port: '3005',

      nativeProtocols: [Object],

      pathname: '/job/results'

    },

    _ended: false,

    _ending: true,

    _redirectCount: 0,

    _redirects: [],

    _requestBodyLength: 227,

    _requestBodyBuffers: [ [Object] ],

    _onNativeResponse: [Function (anonymous)],

    _currentRequest: ClientRequest {

      _events: [Object: null prototype],

      _eventsCount: 7,

      _maxListeners: undefined,

      outputData: [],

      outputSize: 0,

      writable: true,

      destroyed: false,

      _last: true,

      chunkedEncoding: false,

      shouldKeepAlive: false,

      maxRequestsOnConnectionReached: false,

      _defaultKeepAlive: true,

      useChunkedEncodingByDefault: true,

      sendDate: false,

      _removedConnection: false,

      _removedContLen: false,

      _removedTE: false,

      _contentLength: null,

      _hasBody: true,

      _trailer: '',

      finished: false,

      _headerSent: true,

      _closed: false,

      socket: [Socket],

      _header: 'POST /job/results HTTP/1.1\r\n' +

        'Accept: application/json, text/plain, */*\r\n' +

        'Content-Type: application/json\r\n' +

        'User-Agent: axios/0.25.0\r\n' +

        'Content-Length: 227\r\n' +

        'Host: reputation-oracle:3005\r\n' +

        'Connection: close\r\n' +

        '\r\n',

      _keepAliveTimeout: 0,

      _onPendingData: [Function: nop],

      agent: [Agent],

      socketPath: undefined,

      method: 'POST',

      maxHeaderSize: undefined,

      insecureHTTPParser: undefined,

      path: '/job/results',

      _ended: false,

      res: null,

      aborted: false,

      timeoutCb: null,

      upgradeOrConnect: false,

      parser: null,

      maxHeadersCount: null,

      reusedSocket: false,

      host: 'reputation-oracle',

      protocol: 'http:',

      _redirectable: [Circular *1],

      [Symbol(kCapture)]: false,

      [Symbol(kNeedDrain)]: false,

      [Symbol(corked)]: 0,

      [Symbol(kOutHeaders)]: [Object: null prototype]

    },

    _currentUrl: 'http://reputation-oracle:3005/job/results',

    [Symbol(kCapture)]: false

  },

  response: undefined,

  isAxiosError: true,

  toJSON: [Function: toJSON]

}
```

Do you manage to make it work till the end on your side? @vkomodey

**Comment by vkomodey** [comment]
The recording oracle takes the URL from the manifest. So I guess, the reputation oracle URL is wrong(3005 instead of 3006). Could you please re-check your manifest content?

**Comment by foufrix** [comment]
I've redone everything, it's an error on my end because now it's working. 

Sorry about that, I clearly did a typo on the manifest! 

Thank you very much for your help, I'll try with Polygon now!
