### ISSUE TITLE
Making Fortune App work with another Network (Polygon here)

### ISSUE THREAD

**Issue by foufrix** [humanprotocol/fortune#23]
I'm trying to make the fortune app work on a network other than the one deployed on AWS or locally.

I've deployed the Escrow Factory here on polygon Mumbai : https://mumbai.polygonscan.com/address/0x5D65C42cF4a140863744889BAd07f246C0211754

It's currently setup to work with the USDC contract (easier to get for testing with faucet already in place): https://mumbai.polygonscan.com/address/0xe11a86849d99f524cac3e7a0ec1241828e332c62

I've changed `constants.js` to work with those contracts : 
```js
export const HMT_ADDRESS = "0xe11A86849d99F524cAC3E7A0Ec1241828e332C62";
export const ESCROW_FACTORY_ADDRESS = "0x5D65C42cF4a140863744889BAd07f246C0211754";
export const REC_ORACLE_ADDRESS = "0x61F9F0B31eacB420553da8BCC59DC617279731Ac";
export const REP_ORACLE_ADDRESS = "0xD979105297fB0eee83F7433fC09279cb5B94fFC6";
export const EXCHANGE_ORACLE_ADDRESS = "0x6b7E3C31F34cF38d1DFC1D9A8A59482028395809";
```

Those steps works ok : 
1. Creation of Escrow
2. Funding and providing manifest.json
```json
{
  "job_title": "Requesting fortunes from the fortunes teller",
  "job_type": "fortune",
  "fortunes_requested": 2,
  "recording_oracle_address": "0x61F9F0B31eacB420553da8BCC59DC617279731Ac",
  "reputation_oracle_address": "0xD979105297fB0eee83F7433fC09279cb5B94fFC6",
  "echange_oracle_address": "0x6b7E3C31F34cF38d1DFC1D9A8A59482028395809",
  "recording_oracle_url": "http://localhost:3005/job/results",
  "reputation_oracle_url": "http://reputation-oracle:3006/job/results",
  "exchange_oracle_url": "http://localhost:3001"
}
```
3.Sending message with the exchange app => Not working
Front : 
<img width="751" alt="image" src="https://user-images.githubusercontent.com/16646581/165174303-1f8653cc-06c7-4cb1-a628-1d6ce1b46144.png">
Back :
<img width="1093" alt="image" src="https://user-images.githubusercontent.com/16646581/165173471-982d40ee-07fc-41e6-a049-7a4e3f4b0211.png">

I have an ABI error. Is this possible because ABI provided is for HMT and not USDC? Or am I missing something else?
<img width="391" alt="image" src="https://user-images.githubusercontent.com/16646581/165174507-ef815420-0faa-41dc-adaa-e1576a67d761.png">

**Comment by foufrix** [comment]
I've tried by deploying an HMT contract providing me 1 000 000 000 HMT here : https://mumbai.polygonscan.com/address/0x558cd800f9F0B02f3B149667bDe003284c867E94

And an Escrow Factory working with this new deployed token here : https://mumbai.polygonscan.com/address/0x0376D26246Eb35FF4F9924cF13E6C05fd0bD7Fb4

Still the same error at the step of sending message with the exchange app

Any idea on how to solve that?

**Comment by vkomodey** [comment]
Hey, @foufrix
What is the source code for the Escrow you deployed?

**Comment by foufrix** [comment]
It's the one from the repo hmt-escrow, I've deployed the branch with polygon update : https://github.com/humanprotocol/hmt-escrow/tree/polygon-escrow-bulk

**Comment by vkomodey** [comment]
Do the recording and reputation oracles have enough matic for making transactions? I see you use addresses from the ganache setup

**Comment by foufrix** [comment]
That's probably the problem effectively, did not think of that! I have to send some Matic to the address holding the oracles right? I'm effectively using the one from ganache setup.
I'll need to send MATIC to those one? : 
```javascript
export const REC_ORACLE_ADDRESS = "0x61F9F0B31eacB420553da8BCC59DC617279731Ac";
export const REP_ORACLE_ADDRESS = "0xD979105297fB0eee83F7433fC09279cb5B94fFC6";
```

**Comment by foufrix** [comment]
I've tried to send some MATIC to both address, still the same issue

**Comment by vkomodey** [comment]
I advise you to use different oracle addresses. Since they post some changes to the Escrow contract, they need matic on their end

**Comment by foufrix** [comment]
I've sent some Matic to those adresses and I still have the issue.

**Comment by vkomodey** [comment]
When is this error happening? I mean, are you trying to send fortune first time or from the second account?

**Comment by foufrix** [comment]
It's the first Time, on the first call for saving first message from the exchange to the recording oracle

**Comment by vkomodey** [comment]
There are 3 places where we do calls to the blockchain in the recording oracle. Could you please do some tracing and check, what is the line where failure is happening?

**Comment by foufrix** [comment]
Yep sure, I added some logging on `recording-oracle/index.js` 
It's crashing at line 42,43 when we define the `Escrow` : 
```js
console.log("2");
const Escrow = new web3.eth.Contract(EscrowABI, escrowAddress);
console.log("3");
console.log("account: ", account);
const escrowRecOracleAddr = await Escrow.methods.recordingOracle().call({ from: account.address });
```

recording-oracle console : 
<img width="1096" alt="image" src="https://user-images.githubusercontent.com/16646581/165759007-a279f539-fba7-4a7e-a083-862145bd0dd5.png">

And the account address has MATIC on it: https://mumbai.polygonscan.com/address/0x61F9F0B31eacB420553da8BCC59DC617279731Ac

What I don't understand though, is how the oracle can be on polygon? I did not deploy them there (as there is no contract to deploy in the fortune app for them)

From what I understand, the oracle are deployed on the local ganache but not on polygon no? Does the app understand that it has to call the oracle on local ganache even though Metamask is on Polygon when I send the fortune message?

**Comment by vkomodey** [comment]
> From what I understand, the oracle is deployed on the local ganache but not on polygon no?
Yes. Each oracle has it's own environment variables. Like contract and hmt addresses, RPC API URL. They all should be changed because it is a different network

**Comment by foufrix** [comment]
Okay! 
Just tried and all is good, Fortune now working on Polygon Mumbai 🥳  I will update the issue in hmt-escrow repo and provide all proof 🍾
