### ISSUE TITLE
Make minio bucket public by default

### ISSUE THREAD

**Issue by posix4e** [humanprotocol/fortune#30]

**Comment by ivhus** [comment]
@vkomodey @posix4e 

By default buckets in Minio are only created with “private” Access Policy, and I haven’t found a way to change this default.

The way to make them public is to change every bucket’s policy seprately, which can be done either manually (in the UI) or by using command-line.

I made a shell script which does it and put it in the machine in ec2-user’s home folder (Virtual machine with Minio is called “Fortune“
http://ec2-3-15-230-238.us-east-2.compute.amazonaws.com:9001/)

In this script you pass in variable MINIO_BUCKETS value the buckets to make them public

**Comment by portuu3** [comment]
Done in monorepo
