### ISSUE TITLE
Metamask transaction comfirmation doesn't want to pass[Bug]: 

### ISSUE THREAD

**Issue by AzizBardi** [humanprotocol/fortune#34]
### Describe the bug

![IMG-20220803-WA0002](https://user-images.githubusercontent.com/43643907/182869015-dd58ab4c-5473-434b-8f97-79324652279b.jpg)
![IMG-20220803-WA0003](https://user-images.githubusercontent.com/43643907/182869065-5def6e74-f938-4521-a9d6-cd525af03589.jpg)

### Steps to reproduce

1.
Followed all the steps in the readme , everything was working perfectly but, still Metamask is not allowing the transaction and doesn't make the confirmations. keeps showing transaction failed.

### Error messages or log output

```shell
Failed to comfirm the transaction (Metamask)
```

### Browser

Chrome, Firefox, Microsoft Edge

**Comment by Jalal-1** [comment]
Hi Aziz, could you try and resetting the transaction history in your Metamask account, you can do this from:

Settings > Advanced > Reset Account

**Comment by AzizBardi** [comment]
> Hi Aziz, could you try and resetting the transaction history in your Metamask account, you can do this from:
> 
> Settings > Advanced > Reset Account

okey, will do and let you know the update , thanks for the response

**Comment by AzizBardi** [comment]
![Capture](https://user-images.githubusercontent.com/43643907/183101665-5e56e55b-62c4-44e5-80f8-13e03410ac58.JPG)

**Comment by AzizBardi** [comment]
hello, as you can see the transaction passet to the other address buit without creating the escrow. do you have any idea about it ? thanks

**Comment by AzizBardi** [comment]
![Capture](https://user-images.githubusercontent.com/43643907/183103333-4cfc78e4-afcb-463d-82a5-505684a05836.JPG)

**Comment by Jalal-1** [comment]
Hi @AzizBardi I have managed to create the escrow, could you paste the logs from the browser developer console..I think this could help in diagnosing your issue.  I would be happy to jump on a call...we could try and figure this out together...https://calendly.com/jalalhmt/30min

**Comment by AzizBardi** [comment]
> Hi @AzizBardi I have managed to create the escrow, could you paste the logs from the browser developer console..I think this could help in diagnosing your issue.  I would be happy to jump on a call...we could try and figure this out together...https://calendly.com/jalalhmt/30min

Hello @Jalal-1 will share some shots of the console meanwhile i am working on it, thanks for the message :) 
Looking forward to talking with you ! Will book a call on calendly :) 
Thanks

**Comment by Jalal-1** [comment]
Hi @AzizBardi further to our call, the local version cannot be run in WSL as it is not possible to activate host mode in docker on WSL.  Please try Linux and let me know if it works.  Thanks

**Comment by AzizBardi** [comment]
Yes i am lunching the project on linux. As soon as i finish with everything i will let you know. For now everything is fine 😀

**Comment by Jalal-1** [comment]
Just adding a comment for others who may experience this issue...tear down docker and remove all images/containers.
