### ISSUE TITLE
Fortune recording oracle store intermediate results

### ISSUE THREAD

**Issue by posix4e** [humanprotocol/fortune#45]
Fortune recording oracle should actually do it's job on smart contract and with steady storage

Currently https://github.com/humanprotocol/fortune/blob/master/examples/recording-oracle/index.js doesn't actually write to the smart contract or store temporary results. This should do both

- [ ] Invoke store_intermediate_results on the smart contract
- [ ] actually store intermediate results on minio or other steady storage mechanism
- [ ] add unit tests for both

**Comment by portuu3** [comment]
Done in monorepo
